FROM node:lts-buster

RUN apt-get update &&\
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    software-properties-common git default-jre postgresql-client &&\
    apt-get clean &&\
    rm -rf /var/lib/apt/lists/*

RUN \
    wget https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.20.1/allure-commandline-2.20.1.zip && \
    unzip allure-commandline-2.20.1.zip -d /allure && \
    rm allure-commandline-2.20.1.zip

ENV PATH "/allure/allure-2.20.1/bin:${PATH}"
RUN yarn global add wrangler
USER node
RUN npm install -g playwright
RUN npx playwright install --with-deps
